// Code generated by gozodgen. DO NOT EDIT.

package anyfixture

import (
	"github.com/kaptinlin/gozod"
)

// Schema returns a generated gozod schema for Values.
// Package-local generated dependencies call their generated schema methods.
func (v Values) Schema() *gozod.ZodStruct[Values, Values] {
	return gozod.Struct[Values](gozod.StructSchema{
		"any":   gozod.Any(),
		"empty": gozod.Any(),
	})
}
