// Code generated by gozodgen. DO NOT EDIT.

package providerfixture

import (
	"github.com/kaptinlin/gozod"
)

// Schema returns a generated gozod schema for Department.
// Package-local generated dependencies call their generated schema methods.
func (d Department) Schema() *gozod.ZodStruct[Department, Department] {
	return gozod.Struct[Department](gozod.StructSchema{
		"name":      gozod.String(),
		"manager":   gozod.LazyTyped[*Employee](func() any { return Employee{}.Schema() }).Optional(),
		"employees": gozod.Slice[*Employee](gozod.LazyTyped[*Employee](func() any { return Employee{}.Schema() })).Optional(),
	})
}
