// Code generated by gozodgen. DO NOT EDIT.

package providerfixture

import (
	"github.com/kaptinlin/gozod"
)

// Schema returns a generated gozod schema for Employee.
// Package-local generated dependencies call their generated schema methods.
func (e Employee) Schema() *gozod.ZodStruct[Employee, Employee] {
	return gozod.Struct[Employee](gozod.StructSchema{
		"name":       gozod.String(),
		"department": gozod.LazyTyped[*Department](func() any { return Department{}.Schema() }).Optional(),
		"reports":    gozod.Slice[*Employee](gozod.LazyTyped[*Employee](func() any { return Employee{}.Schema() })).Optional(),
	})
}
