// Code generated by gozodgen. DO NOT EDIT.

package providerfixture

import (
	"github.com/kaptinlin/gozod"
)

// Schema returns a generated gozod schema for Node.
// Package-local generated dependencies call their generated schema methods.
func (n Node) Schema() *gozod.ZodStruct[Node, Node] {
	return gozod.Struct[Node](gozod.StructSchema{
		"value":            gozod.Int().Gte(1),
		"next":             gozod.LazyTyped[*Node](func() any { return Node{}.Schema() }).Optional(),
		"children":         gozod.Slice[*Node](gozod.LazyTyped[*Node](func() any { return Node{}.Schema() })).Optional(),
		"children_by_name": gozod.Record[string, *Node](gozod.String(), gozod.LazyTyped[*Node](func() any { return Node{}.Schema() })).Optional(),
	})
}
