version: "2"
linters:
  enable:
    - copyloopvar
    - dogsled
    - err113
    - errorlint
    - exhaustive
    - gocritic
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - promlinter
    - revive
    - unconvert
    - whitespace
  settings:
    revive:
      rules:
        - name: unused-parameter
          disabled: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - funlen
          - gochecknoglobals
          - gosec
          - noctx
          - revive
        path: _test\.go
      # Skip QF1008 embedded field selector issues - these are often necessary
      # to avoid infinite recursion when implementing methods on wrapper types
      - linters:
          - staticcheck
        text: "QF1008.*could remove embedded field.*from selector"
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
