// Code generated by gozodgen. DO NOT EDIT.
// Generated at: 2026-01-18T01:12:59+08:00

package testdata

import (
	"github.com/kaptinlin/gozod"
)

// Schema returns a pre-built gozod schema for AllTypesStruct
// This generated function provides zero-reflection validation with optimal performance
func (ats AllTypesStruct) Schema() *gozod.ZodStruct[AllTypesStruct, AllTypesStruct] {
	return gozod.Struct[AllTypesStruct](gozod.StructSchema{
		"int": gozod.Int(),
		"int8": gozod.Int8(),
		"int16": gozod.Int16(),
		"int32": gozod.Int32(),
		"int64": gozod.Int64(),
		"uint": gozod.Uint(),
		"uint8": gozod.Uint8(),
		"uint16": gozod.Uint16(),
		"uint32": gozod.Uint32(),
		"uint64": gozod.Uint64(),
		"float32": gozod.Float32().Gt(0).Optional(),
		"float64": gozod.Float64().Gt(0).Optional(),
		"complex64": gozod.Complex64().Optional(),
		"complex128": gozod.Complex128().Optional(),
		"bool": gozod.Bool().Default(false).Optional(),
		"ptr_string": gozod.String().Min(1).Optional(),
		"ptr_int": gozod.Int().Gt(0).Optional(),
		"ptr_bool": gozod.Bool().Default(true).Optional(),
	})
}
