// Code generated by gozodgen. DO NOT EDIT.

package testdata

import (
	"github.com/kaptinlin/gozod"
)

// Schema returns a pre-built gozod schema for Category
// This generated function provides zero-reflection validation with optimal performance
func (c Category) Schema() *gozod.ZodStruct[Category, Category] {
	return gozod.Struct[Category](gozod.StructSchema{
		"id":          gozod.UUID(),
		"name":        gozod.String().Min(2),
		"description": gozod.String().Max(500).Optional(),
		"parent_id":   gozod.UUID(),
	})
}
