// Code generated by gozodgen. DO NOT EDIT.

package testdata

import (
	"github.com/kaptinlin/gozod"
)

// Schema returns a generated gozod schema for Category.
// Package-local generated dependencies call their generated schema methods.
func (c Category) Schema() *gozod.ZodStruct[Category, Category] {
	return gozod.Struct[Category](gozod.StructSchema{
		"id":          gozod.UUID(),
		"name":        gozod.String().Min(2),
		"description": gozod.StringPtr().Max(500).Optional(),
		"parent_id":   gozod.UUID().Optional(),
	})
}
