// Code generated by gozodgen. DO NOT EDIT.

package testdata

import (
	"github.com/kaptinlin/gozod"
)

// Schema returns a generated gozod schema for Company.
// Package-local generated dependencies call their generated schema methods.
func (c Company) Schema() *gozod.ZodStruct[Company, Company] {
	return gozod.Struct[Company](gozod.StructSchema{
		"name":  gozod.String(),
		"owner": Employee{}.Schema().Optional(),
	})
}
