// Code generated by gozodgen. DO NOT EDIT.
// Generated at: 2026-01-18T01:12:59+08:00

package testdata

import (
	"github.com/kaptinlin/gozod"
)

// Schema returns a pre-built gozod schema for DefaultStruct
// This generated function provides zero-reflection validation with optimal performance
func (ds DefaultStruct) Schema() *gozod.ZodStruct[DefaultStruct, DefaultStruct] {
	return gozod.Struct[DefaultStruct](gozod.StructSchema{
		"str": gozod.String().Default("hello").Optional(),
		"num": gozod.Int().Default(42).Optional(),
		"float": gozod.Float64().Default(3.14).Optional(),
		"bool": gozod.Bool().Default(true).Optional(),
		"slice": gozod.Slice(gozod.String()).Default([]string{"a", "b"}).Optional(),
		"int_slice": gozod.Slice(gozod.Int()).Default([]int{1, 2, 3}).Optional(),
		"map": gozod.Record(gozod.String()).Default(map[string]string{"k": "v"}).Optional(),
	})
}
