// Code generated by gozodgen. DO NOT EDIT.

package testdata

import (
	"github.com/kaptinlin/gozod"
)

// Schema returns a pre-built gozod schema for DefaultStruct
// This generated function provides zero-reflection validation with optimal performance
func (ds DefaultStruct) Schema() *gozod.ZodStruct[DefaultStruct, DefaultStruct] {
	return gozod.Struct[DefaultStruct](gozod.StructSchema{
		"str":       gozod.String().Optional().Default("hello"),
		"num":       gozod.Int().Optional().Default(42),
		"float":     gozod.Float64().Optional().Default(3.14),
		"bool":      gozod.Bool().Optional().Default(true),
		"slice":     gozod.Slice(gozod.String()).Optional().Default([]string{"a", "b"}),
		"int_slice": gozod.Slice(gozod.Int()).Optional().Default([]int{1, 2, 3}),
		"map":       gozod.Record(gozod.String()).Optional().Default(map[string]string{"k": "v"}),
	})
}
