// Code generated by gozodgen. DO NOT EDIT.
// Generated at: 2026-01-18T01:12:59+08:00

package testdata

import (
	"github.com/kaptinlin/gozod"
)

// Schema returns a pre-built gozod schema for Department
// This generated function provides zero-reflection validation with optimal performance
func (d Department) Schema() *gozod.ZodStruct[Department, Department] {
	return gozod.Struct[Department](gozod.StructSchema{
		"name": gozod.String(),
		"manager": gozod.FromStruct[Employee]().Optional(),
		"employees": gozod.Slice(gozod.FromStruct[Employee]()).Optional(),
	})
}
