// Code generated by gozodgen. DO NOT EDIT.
// Generated at: 2026-01-18T01:12:59+08:00

package testdata

import (
	"github.com/kaptinlin/gozod"
)

// Schema returns a pre-built gozod schema for Employee
// This generated function provides zero-reflection validation with optimal performance
func (e Employee) Schema() *gozod.ZodStruct[Employee, Employee] {
	return gozod.Struct[Employee](gozod.StructSchema{
		"name": gozod.String(),
		"department": gozod.FromStruct[Department]().Optional(),
		"reports": gozod.Slice(gozod.Lazy(func() gozod.ZodType[any] { return gozod.FromStruct[Employee]() })).Optional(),
	})
}
