// Code generated by gozodgen. DO NOT EDIT.
// Generated at: 2026-01-18T01:12:59+08:00

package testdata

import (
	"github.com/kaptinlin/gozod"
)

// Schema returns a pre-built gozod schema for FloatDefaultStruct
// This generated function provides zero-reflection validation with optimal performance
func (fds FloatDefaultStruct) Schema() *gozod.ZodStruct[FloatDefaultStruct, FloatDefaultStruct] {
	return gozod.Struct[FloatDefaultStruct](gozod.StructSchema{
		"float_slice": gozod.Slice(gozod.Float64()).Default([]float64{1.1, 2.2}).Optional(),
		"bool_slice": gozod.Slice(gozod.Bool()).Default([]bool{true, false}).Optional(),
	})
}
