// Code generated by gozodgen. DO NOT EDIT.
// Generated at: 2026-01-18T01:12:59+08:00

package testdata

import (
	"github.com/kaptinlin/gozod"
)

// Schema returns a pre-built gozod schema for FloatPrefaultStruct
// This generated function provides zero-reflection validation with optimal performance
func (fps FloatPrefaultStruct) Schema() *gozod.ZodStruct[FloatPrefaultStruct, FloatPrefaultStruct] {
	return gozod.Struct[FloatPrefaultStruct](gozod.StructSchema{
		"float_slice": gozod.Slice(gozod.Float64()).Prefault([]float64{3.3, 4.4}).Optional(),
		"bool_slice": gozod.Slice(gozod.Bool()).Prefault([]bool{false, true}).Optional(),
	})
}
