// Code generated by gozodgen. DO NOT EDIT.
// Generated at: 2026-01-18T01:12:59+08:00

package testdata

import (
	"github.com/kaptinlin/gozod"
)

// Schema returns a pre-built gozod schema for InterfaceMapPrefaultStruct
// This generated function provides zero-reflection validation with optimal performance
func (imps InterfaceMapPrefaultStruct) Schema() *gozod.ZodStruct[InterfaceMapPrefaultStruct, InterfaceMapPrefaultStruct] {
	return gozod.Struct[InterfaceMapPrefaultStruct](gozod.StructSchema{
		"data": gozod.Record(gozod.Any()).Prefault(map[string]interface{}{"x": 99, "y": "test"}).Optional(),
	})
}
