// Code generated by gozodgen. DO NOT EDIT.

package testdata

import (
	"github.com/kaptinlin/gozod"
)

// Schema returns a generated gozod schema for InterfaceMapStruct.
// Package-local generated dependencies call their generated schema methods.
func (ims InterfaceMapStruct) Schema() *gozod.ZodStruct[InterfaceMapStruct, InterfaceMapStruct] {
	return gozod.Struct[InterfaceMapStruct](gozod.StructSchema{
		"data": gozod.Record(gozod.Any()).Optional().Default(map[string]interface{}{"a": 1, "b": "two", "c": true}),
	})
}
