// Code generated by gozodgen. DO NOT EDIT.

package testdata

import (
	"github.com/kaptinlin/gozod"
)

// Schema returns a pre-built gozod schema for InterfaceMapStruct
// This generated function provides zero-reflection validation with optimal performance
func (ims InterfaceMapStruct) Schema() *gozod.ZodStruct[InterfaceMapStruct, InterfaceMapStruct] {
	return gozod.Struct[InterfaceMapStruct](gozod.StructSchema{
		"data": gozod.Record(gozod.Any()).Optional().Default(map[string]interface{}{"a": 1, "b": "two", "c": true}),
	})
}
