// Code generated by gozodgen. DO NOT EDIT.

package testdata

import (
	"github.com/kaptinlin/gozod"
)

// Schema returns a generated gozod schema for InterfaceMapPrefaultStruct.
// Package-local generated dependencies call their generated schema methods.
func (imps InterfaceMapPrefaultStruct) Schema() *gozod.ZodStruct[InterfaceMapPrefaultStruct, InterfaceMapPrefaultStruct] {
	return gozod.Struct[InterfaceMapPrefaultStruct](gozod.StructSchema{
		"data": gozod.Record[string, unknown](gozod.String(), gozod.Any()).Optional().Prefault(map[string]interface{}{"x": 99, "y": "test"}),
	})
}
