// Code generated by gozodgen. DO NOT EDIT.

package testdata

import (
	"github.com/kaptinlin/gozod"
)

// Schema returns a pre-built gozod schema for InvalidTagStruct
// This generated function provides zero-reflection validation with optimal performance
func (its InvalidTagStruct) Schema() *gozod.ZodStruct[InvalidTagStruct, InvalidTagStruct] {
	return gozod.Struct[InvalidTagStruct](gozod.StructSchema{
		"Name": gozod.String().Optional(),
	})
}
