// Code generated by gozodgen. DO NOT EDIT.

package testdata

import (
	"github.com/kaptinlin/gozod"
)

// Schema returns a generated gozod schema for InvalidTagStruct.
// Package-local generated dependencies call their generated schema methods.
func (its InvalidTagStruct) Schema() *gozod.ZodStruct[InvalidTagStruct, InvalidTagStruct] {
	return gozod.Struct[InvalidTagStruct](gozod.StructSchema{
		"Name": gozod.String().Optional(),
	})
}
