// Code generated by gozodgen. DO NOT EDIT.

package testdata

import (
	"github.com/kaptinlin/gozod"
)

// Schema returns a pre-built gozod schema for MixedTagStruct
// This generated function provides zero-reflection validation with optimal performance
func (mts MixedTagStruct) Schema() *gozod.ZodStruct[MixedTagStruct, MixedTagStruct] {
	return gozod.Struct[MixedTagStruct](gozod.StructSchema{
		"id":     gozod.UUID(),
		"Active": gozod.Bool().Optional().Default(true),
	})
}
