// Code generated by gozodgen. DO NOT EDIT.
// Generated at: 2026-01-18T01:12:59+08:00

package testdata

import (
	"github.com/kaptinlin/gozod"
)

// Schema returns a pre-built gozod schema for MixedTagStruct
// This generated function provides zero-reflection validation with optimal performance
func (mts MixedTagStruct) Schema() *gozod.ZodStruct[MixedTagStruct, MixedTagStruct] {
	return gozod.Struct[MixedTagStruct](gozod.StructSchema{
		"id": gozod.Uuid(),
		"Active": gozod.Bool().Default(true).Optional(),
	})
}
