// Code generated by gozodgen. DO NOT EDIT.

package testdata

import (
	"github.com/kaptinlin/gozod"
)

// Schema returns a generated gozod schema for MixedTagStruct.
// Package-local generated dependencies call their generated schema methods.
func (mts MixedTagStruct) Schema() *gozod.ZodStruct[MixedTagStruct, MixedTagStruct] {
	return gozod.Struct[MixedTagStruct](gozod.StructSchema{
		"id":     gozod.UUID(),
		"Active": gozod.Bool().Optional().Default(true),
	})
}
