// Code generated by gozodgen. DO NOT EDIT.

package testdata

import (
	"github.com/kaptinlin/gozod"
)

// Schema returns a pre-built gozod schema for Node
// This generated function provides zero-reflection validation with optimal performance
func (n Node) Schema() *gozod.ZodStruct[Node, Node] {
	return gozod.Struct[Node](gozod.StructSchema{
		"value":    gozod.Int(),
		"next":     gozod.Lazy(func() gozod.ZodType[any] { return gozod.FromStruct[Node]() }).Optional(),
		"children": gozod.Slice(gozod.Lazy(func() gozod.ZodType[any] { return gozod.FromStruct[Node]() })).Optional(),
	})
}
