// Code generated by gozodgen. DO NOT EDIT.
// Generated at: 2026-01-18T01:12:59+08:00

package testdata

import (
	"github.com/kaptinlin/gozod"
)

// Schema returns a pre-built gozod schema for Node
// This generated function provides zero-reflection validation with optimal performance
func (n Node) Schema() *gozod.ZodStruct[Node, Node] {
	return gozod.Struct[Node](gozod.StructSchema{
		"value": gozod.Int(),
		"next": gozod.Lazy(func() gozod.ZodType[any] { return gozod.FromStruct[Node]() }).Optional(),
		"children": gozod.Slice(gozod.Lazy(func() gozod.ZodType[any] { return gozod.FromStruct[Node]() })).Optional(),
	})
}
