// Code generated by gozodgen. DO NOT EDIT.

package testdata

import (
	"github.com/kaptinlin/gozod"
)

// Schema returns a pre-built gozod schema for PrefaultStruct
// This generated function provides zero-reflection validation with optimal performance
func (ps PrefaultStruct) Schema() *gozod.ZodStruct[PrefaultStruct, PrefaultStruct] {
	return gozod.Struct[PrefaultStruct](gozod.StructSchema{
		"str":   gozod.String().Optional().Prefault("world"),
		"num":   gozod.Int().Optional().Prefault(100),
		"slice": gozod.Slice(gozod.String()).Optional().Prefault([]string{"x", "y"}),
		"map":   gozod.Record(gozod.String()).Optional().Prefault(map[string]string{"foo": "bar"}),
	})
}
