// Code generated by gozodgen. DO NOT EDIT.

package testdata

import (
	"github.com/kaptinlin/gozod"
)

// Schema returns a generated gozod schema for PrefaultStruct.
// Package-local generated dependencies call their generated schema methods.
func (ps PrefaultStruct) Schema() *gozod.ZodStruct[PrefaultStruct, PrefaultStruct] {
	return gozod.Struct[PrefaultStruct](gozod.StructSchema{
		"str":   gozod.String().Optional().Prefault("world"),
		"num":   gozod.Int().Optional().Prefault(100),
		"slice": gozod.Slice[string](gozod.String()).Optional().Prefault([]string{"x", "y"}),
		"map":   gozod.Record[string, string](gozod.String(), gozod.String()).Optional().Prefault(map[string]string{"foo": "bar"}),
	})
}
