// Code generated by gozodgen. DO NOT EDIT.
// Generated at: 2026-01-18T01:12:59+08:00

package testdata

import (
	"github.com/kaptinlin/gozod"
)

// Schema returns a pre-built gozod schema for PrefaultStruct
// This generated function provides zero-reflection validation with optimal performance
func (ps PrefaultStruct) Schema() *gozod.ZodStruct[PrefaultStruct, PrefaultStruct] {
	return gozod.Struct[PrefaultStruct](gozod.StructSchema{
		"str": gozod.String().Prefault("world").Optional(),
		"num": gozod.Int().Prefault(100).Optional(),
		"slice": gozod.Slice(gozod.String()).Prefault([]string{"x", "y"}).Optional(),
		"map": gozod.Record(gozod.String()).Prefault(map[string]string{"foo": "bar"}).Optional(),
	})
}
