// Code generated by gozodgen. DO NOT EDIT.
// Generated at: 2026-01-18T01:12:59+08:00

package testdata

import (
	"github.com/kaptinlin/gozod"
	"regexp"
)

// Schema returns a pre-built gozod schema for Product
// This generated function provides zero-reflection validation with optimal performance
func (p Product) Schema() *gozod.ZodStruct[Product, Product] {
	return gozod.Struct[Product](gozod.StructSchema{
		"id": gozod.UUID(),
		"sku": gozod.String().Regex(regexp.MustCompile("^[A-Z0-9\\-]+$")),
		"name": gozod.String().Min(1).Max(200),
		"price": gozod.Float64().Gt(0.0),
		"currency": gozod.Enum("USD", "EUR", "GBP"),
		"tags": gozod.Slice(gozod.String()).Min(0).Max(10).Optional(),
		"active": gozod.Bool().Default(true).Optional(),
	})
}
