// Code generated by gozodgen. DO NOT EDIT.
// Generated at: 2026-01-18T01:12:59+08:00

package testdata

import (
	"github.com/kaptinlin/gozod"
)

// Schema returns a pre-built gozod schema for User
// This generated function provides zero-reflection validation with optimal performance
func (u User) Schema() *gozod.ZodStruct[User, User] {
	return gozod.Struct[User](gozod.StructSchema{
		"id": gozod.UUID(),
		"name": gozod.String().Min(2).Max(50),
		"email": gozod.String().Email(),
		"age": gozod.Int().Min(18).Max(120),
		"status": gozod.Enum("active", "inactive").Default("active").Optional(),
		"created_at": gozod.Time(),
	})
}
