// Code generated by gozodgen. DO NOT EDIT.

package testdata

import (
	"github.com/kaptinlin/gozod"
	"regexp"
	"strings"
)

// Schema returns a generated gozod schema for ValidatorStruct.
// Package-local generated dependencies call their generated schema methods.
func (vs ValidatorStruct) Schema() *gozod.ZodStruct[ValidatorStruct, ValidatorStruct] {
	return gozod.Struct[ValidatorStruct](gozod.StructSchema{
		"email":   gozod.Email().Optional(),
		"url":     gozod.URL().Optional(),
		"uuid":    gozod.UUID().Optional(),
		"ipv4":    gozod.IPv4().Optional(),
		"ipv6":    gozod.IPv6().Optional(),
		"regex":   gozod.String().Regex(regexp.MustCompile("^[A-Z]+$")).Optional(),
		"trim":    gozod.String().Trim().Optional(),
		"lower":   gozod.String().ToLowerCase().Optional(),
		"upper":   gozod.String().ToUpperCase().Optional(),
		"nilable": gozod.StringPtr().Nilable().Optional(),
		"gt":      gozod.Int().Gt(0).Optional(),
		"gte":     gozod.Int().Gte(0).Optional(),
		"lt":      gozod.Int().Lt(100).Optional(),
		"lte":     gozod.Int().Lte(100).Optional(),
	})
}
