// Code generated by gozodgen. DO NOT EDIT.

package namedscalarfixture

import (
	"github.com/kaptinlin/gozod"
)

// Schema returns a generated gozod schema for Scalars.
// Package-local generated dependencies call their generated schema methods.
func (s Scalars) Schema() *gozod.ZodStruct[Scalars, Scalars] {
	return gozod.Struct[Scalars](gozod.StructSchema{
		"id":            gozod.String().Min(2),
		"count":         gozod.Int64().Positive(),
		"active":        gozod.Bool(),
		"alias":         gozod.String(),
		"pointer":       gozod.StringPtr(),
		"slice":         gozod.Slice[string](gozod.String()),
		"map":           gozod.Record[string, int64](gozod.String(), gozod.Int64()),
		"array":         gozod.Slice[string](gozod.String()).Length(2),
		"default_slice": gozod.Slice[string](gozod.String()).Optional().Default([]string{"primary", "backup"}),
		"prefault_map":  gozod.Record[string, string](gozod.String(), gozod.String()).Optional().Prefault(map[string]string{"primary": "user-1"}),
	})
}
