//go:build contractcheck

package types

// Compile-time interface contract verification.
//
// These assertions keep three layers aligned:
//   - minimal runtime contracts in core/interfaces.go
//   - fluent contracts in core/constraints.go
//   - concrete schema implementations in types/
//
// If a schema type drifts from the expected interface surface, compilation
// fails with a clear type error.
//
// Keeping this file behind the opt-in `contractcheck` build tag prevents the
// self-referential generic assertions from dominating default `go test` and
// `golangci-lint` runs. Enable it explicitly when auditing interface coverage.

import (
	"math/big"
	"time"

	"github.com/kaptinlin/gozod/core"
)

// --- Describable constraint verification ---
// Ensures each schema type has: Describe(string) Self, Meta(GlobalMeta) Self, Internals()

var (
	_ core.Describable[*ZodAny[any, any]]                          = (*ZodAny[any, any])(nil)
	_ core.Describable[*ZodArray[any, any]]                        = (*ZodArray[any, any])(nil)
	_ core.Describable[*ZodBigInt[*big.Int]]                       = (*ZodBigInt[*big.Int])(nil)
	_ core.Describable[*ZodBool[bool]]                             = (*ZodBool[bool])(nil)
	_ core.Describable[*ZodComplex[complex128]]                    = (*ZodComplex[complex128])(nil)
	_ core.Describable[*ZodDiscriminatedUnion[any, any]]           = (*ZodDiscriminatedUnion[any, any])(nil)
	_ core.Describable[*ZodEnum[string, string]]                   = (*ZodEnum[string, string])(nil)
	_ core.Describable[*ZodFile[string, string]]                   = (*ZodFile[string, string])(nil)
	_ core.Describable[*ZodFloatTyped[float64, float64]]           = (*ZodFloatTyped[float64, float64])(nil)
	_ core.Describable[*ZodFunction[any]]                          = (*ZodFunction[any])(nil)
	_ core.Describable[*ZodIntegerTyped[int, int]]                 = (*ZodIntegerTyped[int, int])(nil)
	_ core.Describable[*ZodIntersection[any, any]]                 = (*ZodIntersection[any, any])(nil)
	_ core.Describable[*ZodLazy[any]]                              = (*ZodLazy[any])(nil)
	_ core.Describable[*ZodLiteral[string, string]]                = (*ZodLiteral[string, string])(nil)
	_ core.Describable[*ZodMap[map[any]any, map[any]any]]          = (*ZodMap[map[any]any, map[any]any])(nil)
	_ core.Describable[*ZodNever[any, any]]                        = (*ZodNever[any, any])(nil)
	_ core.Describable[*ZodNil[any, any]]                          = (*ZodNil[any, any])(nil)
	_ core.Describable[*ZodObject[map[string]any, map[string]any]] = (*ZodObject[map[string]any, map[string]any])(nil)
	_ core.Describable[*ZodRecord[map[string]any, map[string]any]] = (*ZodRecord[map[string]any, map[string]any])(nil)
	_ core.Describable[*ZodSet[string, map[string]struct{}]]       = (*ZodSet[string, map[string]struct{}])(nil)
	_ core.Describable[*ZodSlice[any, any]]                        = (*ZodSlice[any, any])(nil)
	_ core.Describable[*ZodString[string]]                         = (*ZodString[string])(nil)
	_ core.Describable[*ZodEmail[string]]                          = (*ZodEmail[string])(nil)
	_ core.Describable[*ZodEmail[*string]]                         = (*ZodEmail[*string])(nil)
	_ core.Describable[*ZodGUID[string]]                           = (*ZodGUID[string])(nil)
	_ core.Describable[*ZodGUID[*string]]                          = (*ZodGUID[*string])(nil)
	_ core.Describable[*ZodCUID[string]]                           = (*ZodCUID[string])(nil)
	_ core.Describable[*ZodCUID[*string]]                          = (*ZodCUID[*string])(nil)
	_ core.Describable[*ZodCUID2[string]]                          = (*ZodCUID2[string])(nil)
	_ core.Describable[*ZodCUID2[*string]]                         = (*ZodCUID2[*string])(nil)
	_ core.Describable[*ZodULID[string]]                           = (*ZodULID[string])(nil)
	_ core.Describable[*ZodULID[*string]]                          = (*ZodULID[*string])(nil)
	_ core.Describable[*ZodXID[string]]                            = (*ZodXID[string])(nil)
	_ core.Describable[*ZodXID[*string]]                           = (*ZodXID[*string])(nil)
	_ core.Describable[*ZodKSUID[string]]                          = (*ZodKSUID[string])(nil)
	_ core.Describable[*ZodKSUID[*string]]                         = (*ZodKSUID[*string])(nil)
	_ core.Describable[*ZodNanoID[string]]                         = (*ZodNanoID[string])(nil)
	_ core.Describable[*ZodNanoID[*string]]                        = (*ZodNanoID[*string])(nil)
	_ core.Describable[*ZodUUID[string]]                           = (*ZodUUID[string])(nil)
	_ core.Describable[*ZodUUID[*string]]                          = (*ZodUUID[*string])(nil)
	_ core.Describable[*ZodIPv4[string]]                           = (*ZodIPv4[string])(nil)
	_ core.Describable[*ZodIPv4[*string]]                          = (*ZodIPv4[*string])(nil)
	_ core.Describable[*ZodIPv6[string]]                           = (*ZodIPv6[string])(nil)
	_ core.Describable[*ZodIPv6[*string]]                          = (*ZodIPv6[*string])(nil)
	_ core.Describable[*ZodCIDRv4[string]]                         = (*ZodCIDRv4[string])(nil)
	_ core.Describable[*ZodCIDRv4[*string]]                        = (*ZodCIDRv4[*string])(nil)
	_ core.Describable[*ZodCIDRv6[string]]                         = (*ZodCIDRv6[string])(nil)
	_ core.Describable[*ZodCIDRv6[*string]]                        = (*ZodCIDRv6[*string])(nil)
	_ core.Describable[*ZodURL[string]]                            = (*ZodURL[string])(nil)
	_ core.Describable[*ZodURL[*string]]                           = (*ZodURL[*string])(nil)
	_ core.Describable[*ZodHostname[string]]                       = (*ZodHostname[string])(nil)
	_ core.Describable[*ZodHostname[*string]]                      = (*ZodHostname[*string])(nil)
	_ core.Describable[*ZodMAC[string]]                            = (*ZodMAC[string])(nil)
	_ core.Describable[*ZodMAC[*string]]                           = (*ZodMAC[*string])(nil)
	_ core.Describable[*ZodE164[string]]                           = (*ZodE164[string])(nil)
	_ core.Describable[*ZodE164[*string]]                          = (*ZodE164[*string])(nil)
	_ core.Describable[*ZodIso[string]]                            = (*ZodIso[string])(nil)
	_ core.Describable[*ZodIso[*string]]                           = (*ZodIso[*string])(nil)
	_ core.Describable[*ZodEmoji[string]]                          = (*ZodEmoji[string])(nil)
	_ core.Describable[*ZodEmoji[*string]]                         = (*ZodEmoji[*string])(nil)
	_ core.Describable[*ZodJWT[string]]                            = (*ZodJWT[string])(nil)
	_ core.Describable[*ZodJWT[*string]]                           = (*ZodJWT[*string])(nil)
	_ core.Describable[*ZodBase64[string]]                         = (*ZodBase64[string])(nil)
	_ core.Describable[*ZodBase64[*string]]                        = (*ZodBase64[*string])(nil)
	_ core.Describable[*ZodBase64URL[string]]                      = (*ZodBase64URL[string])(nil)
	_ core.Describable[*ZodBase64URL[*string]]                     = (*ZodBase64URL[*string])(nil)
	_ core.Describable[*ZodHex[string]]                            = (*ZodHex[string])(nil)
	_ core.Describable[*ZodHex[*string]]                           = (*ZodHex[*string])(nil)
	_ core.Describable[*ZodStringBool[bool]]                       = (*ZodStringBool[bool])(nil)
	_ core.Describable[*ZodStruct[any, any]]                       = (*ZodStruct[any, any])(nil)
	_ core.Describable[*ZodTime[time.Time]]                        = (*ZodTime[time.Time])(nil)
	_ core.Describable[*ZodTuple[[]any, []any]]                    = (*ZodTuple[[]any, []any])(nil)
	_ core.Describable[*ZodUnion[any, any]]                        = (*ZodUnion[any, any])(nil)
	_ core.Describable[*ZodUnknown[any, any]]                      = (*ZodUnknown[any, any])(nil)
	_ core.Describable[*ZodXor[any, any]]                          = (*ZodXor[any, any])(nil)
)

// --- Refineable constraint verification ---
// Ensures each schema type has: RefineAny(func(any) bool, ...any) Self, Internals()

var (
	_ core.Refineable[*ZodAny[any, any]]                          = (*ZodAny[any, any])(nil)
	_ core.Refineable[*ZodArray[any, any]]                        = (*ZodArray[any, any])(nil)
	_ core.Refineable[*ZodBigInt[*big.Int]]                       = (*ZodBigInt[*big.Int])(nil)
	_ core.Refineable[*ZodBool[bool]]                             = (*ZodBool[bool])(nil)
	_ core.Refineable[*ZodComplex[complex128]]                    = (*ZodComplex[complex128])(nil)
	_ core.Refineable[*ZodDiscriminatedUnion[any, any]]           = (*ZodDiscriminatedUnion[any, any])(nil)
	_ core.Refineable[*ZodEnum[string, string]]                   = (*ZodEnum[string, string])(nil)
	_ core.Refineable[*ZodFile[string, string]]                   = (*ZodFile[string, string])(nil)
	_ core.Refineable[*ZodFloatTyped[float64, float64]]           = (*ZodFloatTyped[float64, float64])(nil)
	_ core.Refineable[*ZodFunction[any]]                          = (*ZodFunction[any])(nil)
	_ core.Refineable[*ZodIntegerTyped[int, int]]                 = (*ZodIntegerTyped[int, int])(nil)
	_ core.Refineable[*ZodIntersection[any, any]]                 = (*ZodIntersection[any, any])(nil)
	_ core.Refineable[*ZodLazy[any]]                              = (*ZodLazy[any])(nil)
	_ core.Refineable[*ZodLiteral[string, string]]                = (*ZodLiteral[string, string])(nil)
	_ core.Refineable[*ZodMap[map[any]any, map[any]any]]          = (*ZodMap[map[any]any, map[any]any])(nil)
	_ core.Refineable[*ZodNever[any, any]]                        = (*ZodNever[any, any])(nil)
	_ core.Refineable[*ZodNil[any, any]]                          = (*ZodNil[any, any])(nil)
	_ core.Refineable[*ZodObject[map[string]any, map[string]any]] = (*ZodObject[map[string]any, map[string]any])(nil)
	_ core.Refineable[*ZodRecord[map[string]any, map[string]any]] = (*ZodRecord[map[string]any, map[string]any])(nil)
	_ core.Refineable[*ZodSet[string, map[string]struct{}]]       = (*ZodSet[string, map[string]struct{}])(nil)
	_ core.Refineable[*ZodSlice[any, any]]                        = (*ZodSlice[any, any])(nil)
	_ core.Refineable[*ZodString[string]]                         = (*ZodString[string])(nil)
	_ core.Refineable[*ZodEmail[string]]                          = (*ZodEmail[string])(nil)
	_ core.Refineable[*ZodEmail[*string]]                         = (*ZodEmail[*string])(nil)
	_ core.Refineable[*ZodGUID[string]]                           = (*ZodGUID[string])(nil)
	_ core.Refineable[*ZodGUID[*string]]                          = (*ZodGUID[*string])(nil)
	_ core.Refineable[*ZodCUID[string]]                           = (*ZodCUID[string])(nil)
	_ core.Refineable[*ZodCUID[*string]]                          = (*ZodCUID[*string])(nil)
	_ core.Refineable[*ZodCUID2[string]]                          = (*ZodCUID2[string])(nil)
	_ core.Refineable[*ZodCUID2[*string]]                         = (*ZodCUID2[*string])(nil)
	_ core.Refineable[*ZodULID[string]]                           = (*ZodULID[string])(nil)
	_ core.Refineable[*ZodULID[*string]]                          = (*ZodULID[*string])(nil)
	_ core.Refineable[*ZodXID[string]]                            = (*ZodXID[string])(nil)
	_ core.Refineable[*ZodXID[*string]]                           = (*ZodXID[*string])(nil)
	_ core.Refineable[*ZodKSUID[string]]                          = (*ZodKSUID[string])(nil)
	_ core.Refineable[*ZodKSUID[*string]]                         = (*ZodKSUID[*string])(nil)
	_ core.Refineable[*ZodNanoID[string]]                         = (*ZodNanoID[string])(nil)
	_ core.Refineable[*ZodNanoID[*string]]                        = (*ZodNanoID[*string])(nil)
	_ core.Refineable[*ZodUUID[string]]                           = (*ZodUUID[string])(nil)
	_ core.Refineable[*ZodUUID[*string]]                          = (*ZodUUID[*string])(nil)
	_ core.Refineable[*ZodIPv4[string]]                           = (*ZodIPv4[string])(nil)
	_ core.Refineable[*ZodIPv4[*string]]                          = (*ZodIPv4[*string])(nil)
	_ core.Refineable[*ZodIPv6[string]]                           = (*ZodIPv6[string])(nil)
	_ core.Refineable[*ZodIPv6[*string]]                          = (*ZodIPv6[*string])(nil)
	_ core.Refineable[*ZodCIDRv4[string]]                         = (*ZodCIDRv4[string])(nil)
	_ core.Refineable[*ZodCIDRv4[*string]]                        = (*ZodCIDRv4[*string])(nil)
	_ core.Refineable[*ZodCIDRv6[string]]                         = (*ZodCIDRv6[string])(nil)
	_ core.Refineable[*ZodCIDRv6[*string]]                        = (*ZodCIDRv6[*string])(nil)
	_ core.Refineable[*ZodURL[string]]                            = (*ZodURL[string])(nil)
	_ core.Refineable[*ZodURL[*string]]                           = (*ZodURL[*string])(nil)
	_ core.Refineable[*ZodHostname[string]]                       = (*ZodHostname[string])(nil)
	_ core.Refineable[*ZodHostname[*string]]                      = (*ZodHostname[*string])(nil)
	_ core.Refineable[*ZodMAC[string]]                            = (*ZodMAC[string])(nil)
	_ core.Refineable[*ZodMAC[*string]]                           = (*ZodMAC[*string])(nil)
	_ core.Refineable[*ZodE164[string]]                           = (*ZodE164[string])(nil)
	_ core.Refineable[*ZodE164[*string]]                          = (*ZodE164[*string])(nil)
	_ core.Refineable[*ZodIso[string]]                            = (*ZodIso[string])(nil)
	_ core.Refineable[*ZodIso[*string]]                           = (*ZodIso[*string])(nil)
	_ core.Refineable[*ZodEmoji[string]]                          = (*ZodEmoji[string])(nil)
	_ core.Refineable[*ZodEmoji[*string]]                         = (*ZodEmoji[*string])(nil)
	_ core.Refineable[*ZodJWT[string]]                            = (*ZodJWT[string])(nil)
	_ core.Refineable[*ZodJWT[*string]]                           = (*ZodJWT[*string])(nil)
	_ core.Refineable[*ZodBase64[string]]                         = (*ZodBase64[string])(nil)
	_ core.Refineable[*ZodBase64[*string]]                        = (*ZodBase64[*string])(nil)
	_ core.Refineable[*ZodBase64URL[string]]                      = (*ZodBase64URL[string])(nil)
	_ core.Refineable[*ZodBase64URL[*string]]                     = (*ZodBase64URL[*string])(nil)
	_ core.Refineable[*ZodHex[string]]                            = (*ZodHex[string])(nil)
	_ core.Refineable[*ZodHex[*string]]                           = (*ZodHex[*string])(nil)
	_ core.Refineable[*ZodStringBool[bool]]                       = (*ZodStringBool[bool])(nil)
	_ core.Refineable[*ZodStruct[any, any]]                       = (*ZodStruct[any, any])(nil)
	_ core.Refineable[*ZodTime[time.Time]]                        = (*ZodTime[time.Time])(nil)
	_ core.Refineable[*ZodUnion[any, any]]                        = (*ZodUnion[any, any])(nil)
	_ core.Refineable[*ZodUnknown[any, any]]                      = (*ZodUnknown[any, any])(nil)
	_ core.Refineable[*ZodXor[any, any]]                          = (*ZodXor[any, any])(nil)
)

// --- StrictZodType contract verification ---
// Ensures representative schema types satisfy the strict parsing contract.

var (
	_ core.StrictZodType[any, any]                                 = (*ZodAny[any, any])(nil)
	_ core.StrictZodType[map[string]any, map[string]any]           = (*ZodObject[map[string]any, map[string]any])(nil)
	_ core.StrictZodType[map[string]any, map[string]any]           = (*ZodRecord[map[string]any, map[string]any])(nil)
	_ core.StrictZodType[[]any, []any]                             = (*ZodTuple[[]any, []any])(nil)
	_ core.StrictZodType[any, any]                                 = (*ZodUnion[any, any])(nil)
	_ core.StrictZodType[any, any]                                 = (*ZodIntersection[any, any])(nil)
	_ core.StrictZodType[any, any]                                 = (*ZodDiscriminatedUnion[any, any])(nil)
	_ core.StrictZodType[any, any]                                 = (*ZodUnknown[any, any])(nil)
	_ core.StrictZodType[any, any]                                 = (*ZodXor[any, any])(nil)
	_ core.StrictZodType[string, string]                           = (*ZodString[string])(nil)
	_ core.StrictZodType[bool, bool]                               = (*ZodBool[bool])(nil)
	_ core.StrictZodType[int, int]                                 = (*ZodIntegerTyped[int, int])(nil)
	_ core.StrictZodType[float64, float64]                         = (*ZodFloatTyped[float64, float64])(nil)
	_ core.StrictZodType[complex128, complex128]                   = (*ZodComplex[complex128])(nil)
	_ core.StrictZodType[time.Time, time.Time]                     = (*ZodTime[time.Time])(nil)
	_ core.StrictZodType[*big.Int, *big.Int]                       = (*ZodBigInt[*big.Int])(nil)
	_ core.StrictZodType[map[string]struct{}, map[string]struct{}] = (*ZodSet[string, map[string]struct{}])(nil)
)
