// Code generated by gozodgen. DO NOT EDIT.

package coercionfixture

import (
	"github.com/kaptinlin/gozod"
	"github.com/kaptinlin/gozod/coerce"
)

// Schema returns a generated gozod schema for CoerceStruct.
// Package-local generated dependencies call their generated schema methods.
func (cs CoerceStruct) Schema() *gozod.ZodStruct[CoerceStruct, CoerceStruct] {
	return gozod.Struct[CoerceStruct](gozod.StructSchema{
		"name":   coerce.String(),
		"email":  coerce.String().Email(),
		"age":    coerce.Int().Gte(1),
		"active": coerce.Bool(),
		"score":  coerce.Float64(),
	})
}
