// Code generated by gozodgen. DO NOT EDIT.

package arrayfixture

import (
	"github.com/kaptinlin/gozod"
)

// Schema returns a generated gozod schema for Arrays.
// Package-local generated dependencies call their generated schema methods.
func (a Arrays) Schema() *gozod.ZodStruct[Arrays, Arrays] {
	return gozod.Struct[Arrays](gozod.StructSchema{
		"fixed":            gozod.Slice[string](gozod.String()).Length(3),
		"dynamic":          gozod.Slice[string](gozod.String()),
		"default_value":    gozod.Slice[string](gozod.String()).Length(2).Optional().Default([]string{"left", "right"}),
		"default_pointer":  gozod.SlicePtr[string](gozod.String()).Length(2).Optional().Default([]string{"north", "south"}),
		"prefault_value":   gozod.Slice[string](gozod.String()).Length(2).Optional().Prefault([]string{"up", "down"}),
		"prefault_pointer": gozod.SlicePtr[string](gozod.String()).Length(2).Optional().Prefault([]string{"east", "west"}),
	})
}
