// Code generated by gozodgen. DO NOT EDIT.

package arrayfixture

import (
	"github.com/kaptinlin/gozod"
)

// Schema returns a generated gozod schema for CompositeArrays.
// Package-local generated dependencies call their generated schema methods.
func (ca CompositeArrays) Schema() *gozod.ZodStruct[CompositeArrays, CompositeArrays] {
	return gozod.Struct[CompositeArrays](gozod.StructSchema{
		"nested":          gozod.Slice[any](gozod.Slice[string](gozod.String()).Length(3)).Length(2),
		"pointer":         gozod.SlicePtr[string](gozod.String()).Length(2),
		"default_nested":  gozod.Slice[any](gozod.Slice[string](gozod.String()).Length(3)).Length(2).Optional().Default([]interface{}{[3]string{"a", "b", "c"}, [3]string{"d", "e", "f"}}),
		"prefault_nested": gozod.Slice[any](gozod.Slice[string](gozod.String()).Length(3)).Length(2).Optional().Prefault([]interface{}{[3]string{"g", "h", "i"}, [3]string{"j", "k", "l"}}),
	})
}
