package main

import (
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"text/template"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestCodeGenerator_ProcessPackage(t *testing.T) {
	tests := []struct {
		name            string
		setupFiles      map[string]string // filename -> content
		config          *GeneratorConfig
		expectError     bool
		expectedFiles   []string
		unexpectedFiles []string
	}{
		{
			name: "simple package with one struct",
			setupFiles: map[string]string{
				"user.go": `package main
import "time"

type User struct {
	ID        string    ` + "`json:\"id\" gozod:\"required,uuid\"`" + `
	Name      string    ` + "`json:\"name\" gozod:\"required,min=2,max=50\"`" + `
	Email     string    ` + "`json:\"email\" gozod:\"required,email\"`" + `
	CreatedAt time.Time ` + "`json:\"created_at\" gozod:\"required\"`" + `
}`,
			},
			config: &GeneratorConfig{
				OutputSuffix: "_gen.go",
				PackageName:  "main",
				Verbose:      false,
				DryRun:       false,
			},
			expectError:   false,
			expectedFiles: []string{"user_gen.go"},
		},
		{
			name: "package with multiple structs",
			setupFiles: map[string]string{
				"models.go": `package main

type User struct {
	ID   string ` + "`gozod:\"required,uuid\"`" + `
	Name string ` + "`gozod:\"required,min=2\"`" + `
}

type Product struct {
	ID    string  ` + "`gozod:\"required,uuid\"`" + `
	Name  string  ` + "`gozod:\"required,min=1\"`" + `
	Price float64 ` + "`gozod:\"required,gt=0\"`" + `
}`,
			},
			config: &GeneratorConfig{
				OutputSuffix: "_schema.go",
				PackageName:  "main",
				Verbose:      false,
				DryRun:       false,
			},
			expectError:   false,
			expectedFiles: []string{"user_schema.go", "product_schema.go"},
		},
		{
			name: "dry run mode",
			setupFiles: map[string]string{
				"user.go": `package main
type User struct {
	Name string ` + "`gozod:\"required\"`" + `
}`,
			},
			config: &GeneratorConfig{
				OutputSuffix: "_gen.go",
				PackageName:  "main",
				Verbose:      false,
				DryRun:       true,
			},
			expectError:     false,
			expectedFiles:   []string{}, // No files should be created in dry run
			unexpectedFiles: []string{"user_gen.go"},
		},
		{
			name: "no structs with gozod tags",
			setupFiles: map[string]string{
				"empty.go": `package main
type User struct {
	Name string ` + "`json:\"name\"`" + ` // No gozod tag
}`,
			},
			config: &GeneratorConfig{
				OutputSuffix: "_gen.go",
				PackageName:  "main",
				Verbose:      false,
				DryRun:       false,
			},
			expectError:     false,
			expectedFiles:   []string{}, // No files should be generated
			unexpectedFiles: []string{"empty_gen.go"},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			helper := NewTestHelper(t)

			// Create test files
			for filename, content := range tt.setupFiles {
				helper.CreateGoFile(filename, content)
			}

			// Override output directory in config
			tt.config.PackageName = "main"

			// Create generator
			generator, err := NewCodeGenerator(tt.config)
			require.NoError(t, err, "Failed to create generator")

			// Update writer to use temp directory
			writer, err := NewFileWriter(helper.GetTempDir(), tt.config.PackageName, tt.config.OutputSuffix, tt.config.DryRun, tt.config.Verbose)
			require.NoError(t, err, "Failed to create writer")
			generator.writer = writer

			// Process package
			err = generator.ProcessPackage(helper.GetTempDir())
			if tt.expectError {
				assert.Error(t, err, "Expected error but got none")
			} else {
				assert.NoError(t, err, "Unexpected error")
			}

			// Check expected files
			for _, expectedFile := range tt.expectedFiles {
				helper.AssertFileExists(expectedFile)
			}

			// Check unexpected files
			for _, unexpectedFile := range tt.unexpectedFiles {
				helper.AssertFileNotExists(unexpectedFile)
			}

			// If files were generated, check their content
			if !tt.config.DryRun && len(tt.expectedFiles) > 0 {
				for _, filename := range tt.expectedFiles {
					content := helper.ReadGeneratedFile(filename)
					helper.AssertValidGoCode(content)
					helper.AssertCodeContains(content,
						"// Code generated by gozodgen. DO NOT EDIT.",
						"github.com/kaptinlin/gozod",
					)
					helper.AssertCodeNotContains(content,
						"github.com/kaptinlin/gozod/core",
					)
				}
			}
		})
	}
}

func TestCodeGenerator_RuleTagName(t *testing.T) {
	helper := NewTestHelper(t)
	helper.CreateGoFile("user.go", `package main
type User struct {
	Name string `+"`json:\"name\" validate:\"required,min=2\" gozod:\"max=99\"`"+`
}`)

	config := &GeneratorConfig{
		OutputSuffix: "_gen.go",
		PackageName:  "main",
		RuleTagName:  "validate",
		DryRun:       false,
	}
	generator, err := NewCodeGenerator(config)
	require.NoError(t, err)

	writer, err := NewFileWriter(helper.GetTempDir(), config.PackageName, config.OutputSuffix, config.DryRun, config.Verbose)
	require.NoError(t, err)
	generator.writer = writer

	err = generator.ProcessPackage(helper.GetTempDir())
	require.NoError(t, err)

	content := helper.ReadGeneratedFile("user_gen.go")
	helper.AssertValidGoCode(content)
	helper.AssertCodeContains(content, `"name": gozod.String().Min(2)`)
	helper.AssertCodeNotContains(content, ".Max(99)")
}

func TestCodeGenerator_CircularReferences(t *testing.T) {
	helper := NewTestHelper(t)

	// Create a file with circular references
	content := `package main

type Node struct {
	Value          int              ` + "`json:\"value\" gozod:\"required\"`" + `
	Next           *Node            ` + "`json:\"next\" gozod:\"\"`" + `
	Children       []*Node          ` + "`json:\"children\" gozod:\"\"`" + `
	ChildrenByName map[string]*Node ` + "`json:\"children_by_name\" gozod:\"\"`" + `
}

type Department struct {
	Name      string      ` + "`json:\"name\" gozod:\"required\"`" + `
	Manager   *Employee   ` + "`json:\"manager\" gozod:\"\"`" + `
	Employees []*Employee ` + "`json:\"employees\" gozod:\"\"`" + `
}

type Employee struct {
	Name       string      ` + "`json:\"name\" gozod:\"required\"`" + `
	Department *Department ` + "`json:\"department\" gozod:\"\"`" + `
	Reports    []*Employee ` + "`json:\"reports\" gozod:\"\"`" + `
}

type Company struct {
	Name  string    ` + "`json:\"name\" gozod:\"required\"`" + `
	Owner *Employee ` + "`json:\"owner\" gozod:\"\"`" + `
}`

	helper.CreateGoFile("circular.go", content)

	config := &GeneratorConfig{
		OutputSuffix: "_gen.go",
		PackageName:  "main",
		Verbose:      false,
		DryRun:       false,
	}

	generator, err := NewCodeGenerator(config)
	require.NoError(t, err, "Failed to create generator")

	// Update writer to use temp directory
	writer, err := NewFileWriter(helper.GetTempDir(), config.PackageName, config.OutputSuffix, config.DryRun, config.Verbose)
	require.NoError(t, err, "Failed to create writer")
	generator.writer = writer

	err = generator.ProcessPackage(helper.GetTempDir())
	require.NoError(t, err, "Failed to process package")

	// Check each generated file exists
	expectedFiles := []string{"node_gen.go", "department_gen.go", "employee_gen.go", "company_gen.go"}

	for _, fileName := range expectedFiles {
		helper.AssertFileExists(fileName)
		content := helper.ReadGeneratedFile(fileName)
		helper.AssertValidGoCode(content)

		// Should not import core
		helper.AssertCodeNotContains(content,
			"github.com/kaptinlin/gozod/core",
		)
	}

	// Check for self-references use Lazy (Node.Next and Employee.Reports)
	nodeContent := helper.ReadGeneratedFile("node_gen.go")
	helper.AssertCodeContains(nodeContent,
		"gozod.LazyTyped[*Node](func() any { return Node{}.Schema() })",
	)

	empContent := helper.ReadGeneratedFile("employee_gen.go")
	helper.AssertCodeContains(empContent,
		"gozod.LazyTyped[*Employee](func() any { return Employee{}.Schema() })",
	)

	// Mutual cycles use lazy generated providers.
	deptContent := helper.ReadGeneratedFile("department_gen.go")
	helper.AssertCodeContains(deptContent,
		"gozod.LazyTyped[*Employee](func() any { return Employee{}.Schema() })",
	)

	helper.AssertCodeContains(empContent,
		"gozod.LazyTyped[*Department](func() any { return Department{}.Schema() })",
	)

	// An acyclic package-local edge calls the generated provider directly.
	companyContent := helper.ReadGeneratedFile("company_gen.go")
	helper.AssertCodeContains(companyContent, "Employee{}.Schema()")
	helper.AssertCodeNotContains(companyContent, "gozod.Lazy(")

	for _, content := range []string{nodeContent, deptContent, empContent, companyContent} {
		helper.AssertCodeNotContains(content, "FromStruct")
	}
}

func TestCodeGenerator_ComplexValidation(t *testing.T) {
	helper := NewTestHelper(t)

	content := `package main

type Product struct {
	ID       string   ` + "`json:\"id\" gozod:\"required,uuid\"`" + `
	SKU      string   ` + "`json:\"sku\" gozod:\"required,regex=^[A-Z0-9\\\\-]+$\"`" + `
	Name     string   ` + "`json:\"name\" gozod:\"required,min=1,max=200\"`" + `
	Price    float64  ` + "`json:\"price\" gozod:\"required,gt=0.0\"`" + `
	Currency string   ` + "`json:\"currency\" gozod:\"required,enum=USD EUR GBP JPY\"`" + `
	Tags     []string ` + "`json:\"tags\" gozod:\"min=0,max=10\"`" + `
	Active   *bool    ` + "`json:\"active\" gozod:\"default=true\"`" + `
}`

	helper.CreateGoFile("product.go", content)

	config := &GeneratorConfig{
		OutputSuffix: "_gen.go",
		PackageName:  "main",
		Verbose:      false,
		DryRun:       false,
	}

	generator, err := NewCodeGenerator(config)
	require.NoError(t, err, "Failed to create generator")

	writer, err := NewFileWriter(helper.GetTempDir(), config.PackageName, config.OutputSuffix, config.DryRun, config.Verbose)
	require.NoError(t, err, "Failed to create writer")
	generator.writer = writer

	err = generator.ProcessPackage(helper.GetTempDir())
	require.NoError(t, err, "Failed to process package")

	helper.AssertFileExists("product_gen.go")

	generatedContent := helper.ReadGeneratedFile("product_gen.go")
	helper.AssertValidGoCode(generatedContent)

	// Check specific validations
	helper.AssertCodeContains(generatedContent,
		`"id":       gozod.UUID()`,
		`.Regex(regexp.MustCompile("^[A-Z0-9\\-]+$"))`,
		`.Min(1).Max(200)`,
		`.Gt(0.0)`,
		`.Enum("USD", "EUR", "GBP", "JPY")`,
		`.Optional().Default(true)`,
	)

	// Should import regexp for regex validation
	helper.AssertImportsCorrect(generatedContent,
		[]string{"github.com/kaptinlin/gozod", "regexp"},
		[]string{"github.com/kaptinlin/gozod/core"},
	)
}

func TestCodeGenerator_RealTestdata(t *testing.T) {
	testFiles := []string{
		"simple_struct.go",
		"complex_struct.go",
		"circular_struct.go",
		"validators.go",
	}

	for _, filename := range testFiles {
		t.Run(filename, func(t *testing.T) {
			// Skip if file doesn't exist
			fullPath := filepath.Join("testdata", filename)
			if _, err := os.Stat(fullPath); os.IsNotExist(err) {
				t.Skipf("Testdata file %s not found", filename)
				return
			}

			helper := NewTestHelper(t)

			// Copy testdata file to temp directory
			content, err := os.ReadFile(fullPath)
			require.NoError(t, err, "Failed to read testdata file")
			helper.CreateGoFile(filename, string(content))

			config := &GeneratorConfig{
				OutputSuffix: "_gen.go",
				PackageName:  "testdata", // Use testdata package name
				Verbose:      false,
				DryRun:       false,
			}

			generator, err := NewCodeGenerator(config)
			require.NoError(t, err, "Failed to create generator")

			writer, err := NewFileWriter(helper.GetTempDir(), config.PackageName, config.OutputSuffix, config.DryRun, config.Verbose)
			require.NoError(t, err, "Failed to create writer")
			generator.writer = writer

			err = generator.ProcessPackage(helper.GetTempDir())
			require.NoError(t, err, "Failed to process %s", filename)

			// Check that generation succeeded
			files := helper.ListGeneratedFiles()
			t.Logf("Generated files for %s: %v", filename, files)

			// Find generated files
			generatedFiles := []string{}
			for _, file := range files {
				if strings.HasSuffix(file, "_gen.go") {
					generatedFiles = append(generatedFiles, file)
				}
			}

			if len(generatedFiles) > 0 {
				for _, genFile := range generatedFiles {
					content := helper.ReadGeneratedFile(genFile)
					helper.AssertValidGoCode(content)
					t.Logf("Successfully generated %s with valid Go code", genFile)
				}
			}
		})
	}
}

func TestCodeGenerator_ProcessPackageReturnsAnalysisError(t *testing.T) {
	helper := NewTestHelper(t)
	helper.CreateGoFile("broken.go", "package main\ntype Broken struct {\n")

	generator, err := NewCodeGenerator(&GeneratorConfig{OutputSuffix: "_gen.go", PackageName: "main"})
	require.NoError(t, err)

	err = generator.ProcessPackage(helper.GetTempDir())
	require.Error(t, err)
	assert.ErrorContains(t, err, "analyze package")
}

func TestCodeGenerator_ProcessPackageLeavesOutputsUnchangedOnTypeError(t *testing.T) {
	helper := NewTestHelper(t)
	helper.CreateGoFile("go.mod", `module example.test/typeerror

go 1.26.5
`)
	helper.CreateGoFile("user.go", `package main

var invalid string = 42

type User struct {
	Name string `+"`gozod:\"required\"`"+`
}

type Product struct {
	Name string `+"`gozod:\"required\"`"+`
}
`)
	want := []byte("existing generated output\n")
	outputPath := filepath.Join(helper.GetTempDir(), "user_gen.go")
	require.NoError(t, os.WriteFile(outputPath, want, 0600))

	generator, err := NewCodeGenerator(&GeneratorConfig{OutputSuffix: "_gen.go", PackageName: "main"})
	require.NoError(t, err)

	err = generator.ProcessPackage(helper.GetTempDir())
	require.Error(t, err)
	got, readErr := os.ReadFile(outputPath)
	require.NoError(t, readErr)
	assert.Equal(t, want, got)
	helper.AssertFileNotExists("product_gen.go")
}

func TestCodeGenerator_ProcessPackageLeavesOutputsUnchangedOnUnsupportedField(t *testing.T) {
	helper := NewTestHelper(t)
	helper.CreateGoFile("models.go", `package main

type Valid struct {
	Name string `+"`gozod:\"required\"`"+`
}

type Broken struct {
	Updates chan int `+"`gozod:\"required\"`"+`
}
`)
	want := []byte("package main\n\nconst existingGeneratedOutput = true\n")
	outputPath := filepath.Join(helper.GetTempDir(), "models_gen.go")
	require.NoError(t, os.WriteFile(outputPath, want, 0600))

	generator, err := NewCodeGenerator(&GeneratorConfig{OutputSuffix: "_gen.go", PackageName: "main"})
	require.NoError(t, err)

	err = generator.ProcessPackage(helper.GetTempDir())
	require.Error(t, err)
	assert.ErrorContains(t, err, "Updates")
	assert.ErrorContains(t, err, "chan int")
	assert.ErrorContains(t, err, "unsupported field type")
	got, readErr := os.ReadFile(outputPath)
	require.NoError(t, readErr)
	assert.Equal(t, want, got)
}

func TestCodeGenerator_ProcessPackageLeavesOutputsUnchangedOnUnsupportedMapKey(t *testing.T) {
	helper := NewTestHelper(t)
	helper.CreateGoFile("models.go", `package main

type Valid struct {
	Name string `+"`gozod:\"required\"`"+`
}

type Broken struct {
	Values map[int]string `+"`gozod:\"required\"`"+`
}
`)
	want := []byte("package main\n\nconst existingGeneratedOutput = true\n")
	outputPath := filepath.Join(helper.GetTempDir(), "models_gen.go")
	require.NoError(t, os.WriteFile(outputPath, want, 0600))

	generator, err := NewCodeGenerator(&GeneratorConfig{OutputSuffix: "_gen.go", PackageName: "main"})
	require.NoError(t, err)

	err = generator.ProcessPackage(helper.GetTempDir())
	require.Error(t, err)
	assert.ErrorContains(t, err, "Values")
	assert.ErrorContains(t, err, "map[int]string")
	assert.ErrorContains(t, err, "unsupported field type")
	got, readErr := os.ReadFile(outputPath)
	require.NoError(t, readErr)
	assert.Equal(t, want, got)
}

func TestCodeGenerator_ProcessPackageDoesNotPublishPartialRenderResults(t *testing.T) {
	tests := []struct {
		name   string
		dryRun bool
	}{
		{name: "files", dryRun: false},
		{name: "dry run output", dryRun: true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			helper := NewTestHelper(t)
			helper.CreateGoFile("models.go", `package main

type First struct {
	Name string `+"`gozod:\"required\"`"+`
}

type Second struct {
	Name string `+"`gozod:\"required\"`"+`
}
`)
			want := []byte("package main\n\nconst existingFirstOutput = true\n")
			firstPath := filepath.Join(helper.GetTempDir(), "first_gen.go")
			if !tt.dryRun {
				require.NoError(t, os.WriteFile(firstPath, want, 0600))
			}

			generator, err := NewCodeGenerator(&GeneratorConfig{
				OutputSuffix: "_gen.go",
				PackageName:  "main",
				DryRun:       tt.dryRun,
			})
			require.NoError(t, err)
			writer, err := NewFileWriter("", "main", "_gen.go", tt.dryRun, false)
			require.NoError(t, err)
			writer.templates = template.Must(template.New("main").Parse(`package main
{{if eq .StructName "Second"}}func ({{else}}const renderedFirst = true{{end}}
`))
			generator.writer = writer

			var output string
			if tt.dryRun {
				readEnd, writeEnd, pipeErr := os.Pipe()
				require.NoError(t, pipeErr)
				originalStdout := os.Stdout
				os.Stdout = writeEnd
				err = generator.ProcessPackage(helper.GetTempDir())
				os.Stdout = originalStdout
				require.NoError(t, writeEnd.Close())
				captured, readErr := io.ReadAll(readEnd)
				require.NoError(t, readErr)
				require.NoError(t, readEnd.Close())
				output = string(captured)
			} else {
				err = generator.ProcessPackage(helper.GetTempDir())
			}

			require.Error(t, err)
			assert.ErrorContains(t, err, "Second")
			if tt.dryRun {
				assert.Empty(t, output)
				helper.AssertFileNotExists("first_gen.go")
			} else {
				got, readErr := os.ReadFile(firstPath)
				require.NoError(t, readErr)
				assert.Equal(t, want, got)
			}
			helper.AssertFileNotExists("second_gen.go")
		})
	}
}

func TestCodeGenerator_ProcessPackageReturnsWriteError(t *testing.T) {
	helper := NewTestHelper(t)
	helper.CreateGoFile("user.go", `package main
type User struct {
	Name string `+"`gozod:\"required\"`"+`
}
`)

	blockedOutput := filepath.Join(helper.GetTempDir(), "user_gen.go")
	require.NoError(t, os.Mkdir(blockedOutput, 0750))

	generator, err := NewCodeGenerator(&GeneratorConfig{OutputSuffix: "_gen.go", PackageName: "main"})
	require.NoError(t, err)

	err = generator.ProcessPackage(helper.GetTempDir())
	require.Error(t, err)
	assert.ErrorContains(t, err, "generate code for struct User")
}

func TestNewCodeGenerator(t *testing.T) {
	tests := []struct {
		name        string
		config      *GeneratorConfig
		expectError bool
	}{
		{
			name: "valid config",
			config: &GeneratorConfig{
				OutputSuffix: "_gen.go",
				PackageName:  "main",
				Verbose:      false,
				DryRun:       false,
			},
			expectError: false,
		},
		{
			name:        "nil config",
			config:      nil,
			expectError: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			generator, err := NewCodeGenerator(tt.config)
			if tt.expectError {
				assert.Error(t, err, "Expected error but got none")
			} else {
				assert.NoError(t, err, "Unexpected error")
			}
			if !tt.expectError {
				assert.NotNil(t, generator, "Expected generator but got nil")
			}
		})
	}
}
