// Code generated by gozodgen. DO NOT EDIT.

package presencefixture

import (
	"github.com/kaptinlin/gozod"
)

// Schema returns a generated gozod schema for Presence.
// Package-local generated dependencies call their generated schema methods.
func (p Presence) Schema() *gozod.ZodStruct[Presence, Presence] {
	return gozod.Struct[Presence](gozod.StructSchema{
		"required_value":            gozod.String().Min(2),
		"optional_value":            gozod.String().Min(2).Optional(),
		"required_pointer":          gozod.StringPtr().Min(2),
		"optional_pointer":          gozod.StringPtr().Min(2).Optional(),
		"required_nilable_value":    gozod.String().Nilable().Min(2),
		"optional_nilable_value":    gozod.String().Nilable().Min(2).Optional(),
		"required_nilable_pointer":  gozod.StringPtr().Nilable().Min(2),
		"optional_nilable_pointer":  gozod.StringPtr().Nilable().Min(2).Optional(),
		"required_default_value":    gozod.String().Default("required"),
		"optional_default_value":    gozod.String().Optional().Default("optional"),
		"required_default_pointer":  gozod.StringPtr().Default("required"),
		"optional_default_pointer":  gozod.StringPtr().Optional().Default("optional"),
		"required_prefault_value":   gozod.String().Prefault("required").Min(2),
		"optional_prefault_value":   gozod.String().Optional().Prefault("optional").Min(2),
		"required_prefault_pointer": gozod.StringPtr().Prefault("required").Min(2),
		"optional_prefault_pointer": gozod.StringPtr().Optional().Prefault("optional").Min(2),
	})
}
