// Code generated by gozodgen. DO NOT EDIT.

package main

import (
	"github.com/kaptinlin/gozod"
	"regexp"
)

// Schema returns a generated gozod schema for Product.
// Package-local generated dependencies call their generated schema methods.
func (p Product) Schema() *gozod.ZodStruct[Product, Product] {
	return gozod.Struct[Product](gozod.StructSchema{
		"id":       gozod.UUID(),
		"sku":      gozod.String().Min(3).Max(50).Regex(regexp.MustCompile("^[A-Z0-9\\-]+$")),
		"name":     gozod.String().Min(1).Max(200),
		"price":    gozod.Float64().Gt(0.0),
		"currency": gozod.Enum("USD", "EUR", "GBP", "JPY"),
		"in_stock": gozod.Bool().Optional().Default(true),
	})
}
